#:schema node_modules/wrangler/config-schema.json
name = "wrl"
main = "src/index.js"
compatibility_date = "2026-03-13"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "wrl-captures"
preview_bucket_name = "wrl-captures-preview"

[[kv_namespaces]]
binding = "KV"
id = "b5cd6168cd32485dba7a90558e5fad29"
preview_id = "d7d4739a73074b9793889046e59c9323"

[[unsafe.bindings]]
name = "CAPTURE_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 10, period = 60 }

[[unsafe.bindings]]
name = "VERIFY_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1002"
simple = { limit = 60, period = 60 }

[browser]
binding = "BROWSER"
